# Generated by Django 2.2.4 on 2019-11-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
