# Generated by Django 2.2.4 on 2019-11-27 00:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0002_auto_20191127_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='print',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
