# Generated by Django 2.2.4 on 2019-10-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0003_auto_20191018_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
